"""init tables

Revision ID: 572f7403f3db
Revises: 
Create Date: 2026-08-12 15:17:06.277950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572f7403f3db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False, comment='scope:Idempotency-Key'),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('response', sa.Text(), nullable=False, comment='首次结果 data 的 JSON'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_idempotency_records_created_at', 'idempotency_records', ['created_at'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False, comment='价格（单位：分，禁止浮点）'),
    sa.Column('type', sa.Integer(), nullable=False, comment='0-免费档 1-付费档'),
    sa.Column('free_flag', sa.Integer(), nullable=False, comment='1-免费 0-付费'),
    sa.Column('status', sa.Integer(), nullable=False, comment='0-禁用（下架） 1-启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.String(length=32), nullable=False, comment='P+YYYYMMDD+5位序列'),
    sa.Column('name_a', sa.String(length=64), nullable=False),
    sa.Column('birth_a', sa.Text(), nullable=False, comment='甲方生辰密文'),
    sa.Column('birth_hour_a', sa.Text(), nullable=True, comment='甲方时辰密文'),
    sa.Column('name_b', sa.String(length=64), nullable=False),
    sa.Column('birth_b', sa.Text(), nullable=False, comment='乙方生辰密文'),
    sa.Column('birth_hour_b', sa.Text(), nullable=True, comment='乙方时辰密文'),
    sa.Column('is_lunar', sa.Boolean(), nullable=False),
    sa.Column('combo_data', sa.Text(), nullable=True, comment='测算因子密文（JSON）'),
    sa.Column('preview_report', sa.Text(), nullable=True, comment='预览报告 JSON'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='S+YYYYMMDD+3位序列'),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('out_trade_no', sa.String(length=64), nullable=False, comment='微信商户订单号=order_no'),
    sa.Column('openid', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False, comment='金额（分）'),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('pay_type', sa.String(length=16), nullable=True, comment='h5/native/jsapi'),
    sa.Column('ad_params', sa.JSON(), nullable=True, comment='磁力投放归因 JSON'),
    sa.Column('fail_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('order_no'),
    sa.UniqueConstraint('out_trade_no')
    )
    op.create_index('ix_orders_profile_id', 'orders', ['profile_id'], unique=False)
    op.create_index('ix_orders_state', 'orders', ['state'], unique=False)
    op.create_table('delivery_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('task_state', sa.String(length=16), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_no'], ['orders.order_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_delivery_tasks_order_no', 'delivery_tasks', ['order_no'], unique=False)
    op.create_table('pay_transactions',
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('pay_type', sa.String(length=16), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('pay_state', sa.String(length=16), nullable=True),
    sa.Column('raw_callback', sa.Text(), nullable=True),
    sa.Column('callback_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_no'], ['orders.order_no'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('ix_pay_transactions_order_no', 'pay_transactions', ['order_no'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=True),
    sa.Column('full_report', sa.Text(), nullable=True, comment='完整报告内容/URL'),
    sa.Column('state', sa.String(length=16), nullable=False, comment='locked/unlocked'),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_no'], ['orders.order_no'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_profile_id'), 'reports', ['profile_id'], unique=False)
    op.create_table('wecom_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('external_userid', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True, comment='活码 state 关联订单/渠道'),
    sa.Column('add_flag', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_no'], ['orders.order_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wecom_contacts_order_no', 'wecom_contacts', ['order_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wecom_contacts_order_no', table_name='wecom_contacts')
    op.drop_table('wecom_contacts')
    op.drop_index(op.f('ix_reports_profile_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_pay_transactions_order_no', table_name='pay_transactions')
    op.drop_table('pay_transactions')
    op.drop_index('ix_delivery_tasks_order_no', table_name='delivery_tasks')
    op.drop_table('delivery_tasks')
    op.drop_index('ix_orders_state', table_name='orders')
    op.drop_index('ix_orders_profile_id', table_name='orders')
    op.drop_table('orders')
    op.drop_table('profiles')
    op.drop_table('products')
    op.drop_index('ix_idempotency_records_created_at', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
